spring:
  config:
    import: optional:configserver:http://config-server:8888/
  application:
    name: auth-service
  cloud:
    config:
      uri: http://config-server:8888

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: auth-service
    preferIpAddress: false

jwt:
  secret: shailesh-secret-key-change-in-production
  expiration-ms: 3600000 # 1 hour

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.shailesh: DEBUG
    org.springframework.security: DEBUG
