spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///app/config
      enabled: true

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: config-server
    preferIpAddress: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
